# Generated by Django 3.2.3 on 2021-05-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='book',
        ),
    ]
